/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppLogningRouteImport } from './routes/app.logning'
import { Route as AppArkivRouteImport } from './routes/app.arkiv'
import { Route as AppAktiviteterRouteImport } from './routes/app.aktiviteter'
import { Route as AppAdminRouteImport } from './routes/app.admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppLogningRoute = AppLogningRouteImport.update({
  id: '/logning',
  path: '/logning',
  getParentRoute: () => AppRoute,
} as any)
const AppArkivRoute = AppArkivRouteImport.update({
  id: '/arkiv',
  path: '/arkiv',
  getParentRoute: () => AppRoute,
} as any)
const AppAktiviteterRoute = AppAktiviteterRouteImport.update({
  id: '/aktiviteter',
  path: '/aktiviteter',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/aktiviteter': typeof AppAktiviteterRoute
  '/app/arkiv': typeof AppArkivRoute
  '/app/logning': typeof AppLogningRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/aktiviteter': typeof AppAktiviteterRoute
  '/app/arkiv': typeof AppArkivRoute
  '/app/logning': typeof AppLogningRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/aktiviteter': typeof AppAktiviteterRoute
  '/app/arkiv': typeof AppArkivRoute
  '/app/logning': typeof AppLogningRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/aktiviteter'
    | '/app/arkiv'
    | '/app/logning'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/aktiviteter'
    | '/app/arkiv'
    | '/app/logning'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/aktiviteter'
    | '/app/arkiv'
    | '/app/logning'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logning': {
      id: '/app/logning'
      path: '/logning'
      fullPath: '/app/logning'
      preLoaderRoute: typeof AppLogningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/arkiv': {
      id: '/app/arkiv'
      path: '/arkiv'
      fullPath: '/app/arkiv'
      preLoaderRoute: typeof AppArkivRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aktiviteter': {
      id: '/app/aktiviteter'
      path: '/aktiviteter'
      fullPath: '/app/aktiviteter'
      preLoaderRoute: typeof AppAktiviteterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAktiviteterRoute: typeof AppAktiviteterRoute
  AppArkivRoute: typeof AppArkivRoute
  AppLogningRoute: typeof AppLogningRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAktiviteterRoute: AppAktiviteterRoute,
  AppArkivRoute: AppArkivRoute,
  AppLogningRoute: AppLogningRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
