/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Verify2faRouteImport } from './routes/verify-2fa'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SletDataRouteImport } from './routes/slet-data'
import { Route as SikkerhedRouteImport } from './routes/sikkerhed'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as Setup2faRouteImport } from './routes/setup-2fa'
import { Route as PrivatlivspolitikRouteImport } from './routes/privatlivspolitik'
import { Route as PriserRouteImport } from './routes/priser'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup.index'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SignupPersonaleRouteImport } from './routes/signup.personale'
import { Route as LoginPersonaleRouteImport } from './routes/login.personale'
import { Route as LoginAdminRouteImport } from './routes/login.admin'
import { Route as CheckoutSuccesRouteImport } from './routes/checkout.succes'
import { Route as CheckoutAnnulleretRouteImport } from './routes/checkout.annulleret'
import { Route as AppLogningRouteImport } from './routes/app.logning'
import { Route as AppIndstillingerRouteImport } from './routes/app.indstillinger'
import { Route as AppArkivRouteImport } from './routes/app.arkiv'
import { Route as AppAktiviteterRouteImport } from './routes/app.aktiviteter'
import { Route as AppAdminRouteImport } from './routes/app.admin'

const Verify2faRoute = Verify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SletDataRoute = SletDataRouteImport.update({
  id: '/slet-data',
  path: '/slet-data',
  getParentRoute: () => rootRouteImport,
} as any)
const SikkerhedRoute = SikkerhedRouteImport.update({
  id: '/sikkerhed',
  path: '/sikkerhed',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const Setup2faRoute = Setup2faRouteImport.update({
  id: '/setup-2fa',
  path: '/setup-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatlivspolitikRoute = PrivatlivspolitikRouteImport.update({
  id: '/privatlivspolitik',
  path: '/privatlivspolitik',
  getParentRoute: () => rootRouteImport,
} as any)
const PriserRoute = PriserRouteImport.update({
  id: '/priser',
  path: '/priser',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignupRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SignupPersonaleRoute = SignupPersonaleRouteImport.update({
  id: '/personale',
  path: '/personale',
  getParentRoute: () => SignupRoute,
} as any)
const LoginPersonaleRoute = LoginPersonaleRouteImport.update({
  id: '/personale',
  path: '/personale',
  getParentRoute: () => LoginRoute,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LoginRoute,
} as any)
const CheckoutSuccesRoute = CheckoutSuccesRouteImport.update({
  id: '/checkout/succes',
  path: '/checkout/succes',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutAnnulleretRoute = CheckoutAnnulleretRouteImport.update({
  id: '/checkout/annulleret',
  path: '/checkout/annulleret',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLogningRoute = AppLogningRouteImport.update({
  id: '/logning',
  path: '/logning',
  getParentRoute: () => AppRoute,
} as any)
const AppIndstillingerRoute = AppIndstillingerRouteImport.update({
  id: '/indstillinger',
  path: '/indstillinger',
  getParentRoute: () => AppRoute,
} as any)
const AppArkivRoute = AppArkivRouteImport.update({
  id: '/arkiv',
  path: '/arkiv',
  getParentRoute: () => AppRoute,
} as any)
const AppAktiviteterRoute = AppAktiviteterRouteImport.update({
  id: '/aktiviteter',
  path: '/aktiviteter',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/priser': typeof PriserRoute
  '/privatlivspolitik': typeof PrivatlivspolitikRoute
  '/setup-2fa': typeof Setup2faRoute
  '/signup': typeof SignupRouteWithChildren
  '/sikkerhed': typeof SikkerhedRoute
  '/slet-data': typeof SletDataRoute
  '/superadmin': typeof SuperadminRoute
  '/verify-2fa': typeof Verify2faRoute
  '/app/admin': typeof AppAdminRoute
  '/app/aktiviteter': typeof AppAktiviteterRoute
  '/app/arkiv': typeof AppArkivRoute
  '/app/indstillinger': typeof AppIndstillingerRoute
  '/app/logning': typeof AppLogningRoute
  '/checkout/annulleret': typeof CheckoutAnnulleretRoute
  '/checkout/succes': typeof CheckoutSuccesRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/personale': typeof LoginPersonaleRoute
  '/signup/personale': typeof SignupPersonaleRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/priser': typeof PriserRoute
  '/privatlivspolitik': typeof PrivatlivspolitikRoute
  '/setup-2fa': typeof Setup2faRoute
  '/sikkerhed': typeof SikkerhedRoute
  '/slet-data': typeof SletDataRoute
  '/superadmin': typeof SuperadminRoute
  '/verify-2fa': typeof Verify2faRoute
  '/app/admin': typeof AppAdminRoute
  '/app/aktiviteter': typeof AppAktiviteterRoute
  '/app/arkiv': typeof AppArkivRoute
  '/app/indstillinger': typeof AppIndstillingerRoute
  '/app/logning': typeof AppLogningRoute
  '/checkout/annulleret': typeof CheckoutAnnulleretRoute
  '/checkout/succes': typeof CheckoutSuccesRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/personale': typeof LoginPersonaleRoute
  '/signup/personale': typeof SignupPersonaleRoute
  '/app': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/signup': typeof SignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/priser': typeof PriserRoute
  '/privatlivspolitik': typeof PrivatlivspolitikRoute
  '/setup-2fa': typeof Setup2faRoute
  '/signup': typeof SignupRouteWithChildren
  '/sikkerhed': typeof SikkerhedRoute
  '/slet-data': typeof SletDataRoute
  '/superadmin': typeof SuperadminRoute
  '/verify-2fa': typeof Verify2faRoute
  '/app/admin': typeof AppAdminRoute
  '/app/aktiviteter': typeof AppAktiviteterRoute
  '/app/arkiv': typeof AppArkivRoute
  '/app/indstillinger': typeof AppIndstillingerRoute
  '/app/logning': typeof AppLogningRoute
  '/checkout/annulleret': typeof CheckoutAnnulleretRoute
  '/checkout/succes': typeof CheckoutSuccesRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/personale': typeof LoginPersonaleRoute
  '/signup/personale': typeof SignupPersonaleRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/priser'
    | '/privatlivspolitik'
    | '/setup-2fa'
    | '/signup'
    | '/sikkerhed'
    | '/slet-data'
    | '/superadmin'
    | '/verify-2fa'
    | '/app/admin'
    | '/app/aktiviteter'
    | '/app/arkiv'
    | '/app/indstillinger'
    | '/app/logning'
    | '/checkout/annulleret'
    | '/checkout/succes'
    | '/login/admin'
    | '/login/personale'
    | '/signup/personale'
    | '/app/'
    | '/login/'
    | '/signup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/priser'
    | '/privatlivspolitik'
    | '/setup-2fa'
    | '/sikkerhed'
    | '/slet-data'
    | '/superadmin'
    | '/verify-2fa'
    | '/app/admin'
    | '/app/aktiviteter'
    | '/app/arkiv'
    | '/app/indstillinger'
    | '/app/logning'
    | '/checkout/annulleret'
    | '/checkout/succes'
    | '/login/admin'
    | '/login/personale'
    | '/signup/personale'
    | '/app'
    | '/login'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/priser'
    | '/privatlivspolitik'
    | '/setup-2fa'
    | '/signup'
    | '/sikkerhed'
    | '/slet-data'
    | '/superadmin'
    | '/verify-2fa'
    | '/app/admin'
    | '/app/aktiviteter'
    | '/app/arkiv'
    | '/app/indstillinger'
    | '/app/logning'
    | '/checkout/annulleret'
    | '/checkout/succes'
    | '/login/admin'
    | '/login/personale'
    | '/signup/personale'
    | '/app/'
    | '/login/'
    | '/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  PriserRoute: typeof PriserRoute
  PrivatlivspolitikRoute: typeof PrivatlivspolitikRoute
  Setup2faRoute: typeof Setup2faRoute
  SignupRoute: typeof SignupRouteWithChildren
  SikkerhedRoute: typeof SikkerhedRoute
  SletDataRoute: typeof SletDataRoute
  SuperadminRoute: typeof SuperadminRoute
  Verify2faRoute: typeof Verify2faRoute
  CheckoutAnnulleretRoute: typeof CheckoutAnnulleretRoute
  CheckoutSuccesRoute: typeof CheckoutSuccesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-2fa': {
      id: '/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof Verify2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slet-data': {
      id: '/slet-data'
      path: '/slet-data'
      fullPath: '/slet-data'
      preLoaderRoute: typeof SletDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sikkerhed': {
      id: '/sikkerhed'
      path: '/sikkerhed'
      fullPath: '/sikkerhed'
      preLoaderRoute: typeof SikkerhedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-2fa': {
      id: '/setup-2fa'
      path: '/setup-2fa'
      fullPath: '/setup-2fa'
      preLoaderRoute: typeof Setup2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatlivspolitik': {
      id: '/privatlivspolitik'
      path: '/privatlivspolitik'
      fullPath: '/privatlivspolitik'
      preLoaderRoute: typeof PrivatlivspolitikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priser': {
      id: '/priser'
      path: '/priser'
      fullPath: '/priser'
      preLoaderRoute: typeof PriserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof SignupRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/signup/personale': {
      id: '/signup/personale'
      path: '/personale'
      fullPath: '/signup/personale'
      preLoaderRoute: typeof SignupPersonaleRouteImport
      parentRoute: typeof SignupRoute
    }
    '/login/personale': {
      id: '/login/personale'
      path: '/personale'
      fullPath: '/login/personale'
      preLoaderRoute: typeof LoginPersonaleRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof LoginRoute
    }
    '/checkout/succes': {
      id: '/checkout/succes'
      path: '/checkout/succes'
      fullPath: '/checkout/succes'
      preLoaderRoute: typeof CheckoutSuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/annulleret': {
      id: '/checkout/annulleret'
      path: '/checkout/annulleret'
      fullPath: '/checkout/annulleret'
      preLoaderRoute: typeof CheckoutAnnulleretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/logning': {
      id: '/app/logning'
      path: '/logning'
      fullPath: '/app/logning'
      preLoaderRoute: typeof AppLogningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/indstillinger': {
      id: '/app/indstillinger'
      path: '/indstillinger'
      fullPath: '/app/indstillinger'
      preLoaderRoute: typeof AppIndstillingerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/arkiv': {
      id: '/app/arkiv'
      path: '/arkiv'
      fullPath: '/app/arkiv'
      preLoaderRoute: typeof AppArkivRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aktiviteter': {
      id: '/app/aktiviteter'
      path: '/aktiviteter'
      fullPath: '/app/aktiviteter'
      preLoaderRoute: typeof AppAktiviteterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAktiviteterRoute: typeof AppAktiviteterRoute
  AppArkivRoute: typeof AppArkivRoute
  AppIndstillingerRoute: typeof AppIndstillingerRoute
  AppLogningRoute: typeof AppLogningRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAktiviteterRoute: AppAktiviteterRoute,
  AppArkivRoute: AppArkivRoute,
  AppIndstillingerRoute: AppIndstillingerRoute,
  AppLogningRoute: AppLogningRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LoginRouteChildren {
  LoginAdminRoute: typeof LoginAdminRoute
  LoginPersonaleRoute: typeof LoginPersonaleRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginAdminRoute: LoginAdminRoute,
  LoginPersonaleRoute: LoginPersonaleRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface SignupRouteChildren {
  SignupPersonaleRoute: typeof SignupPersonaleRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupPersonaleRoute: SignupPersonaleRoute,
  SignupIndexRoute: SignupIndexRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  PriserRoute: PriserRoute,
  PrivatlivspolitikRoute: PrivatlivspolitikRoute,
  Setup2faRoute: Setup2faRoute,
  SignupRoute: SignupRouteWithChildren,
  SikkerhedRoute: SikkerhedRoute,
  SletDataRoute: SletDataRoute,
  SuperadminRoute: SuperadminRoute,
  Verify2faRoute: Verify2faRoute,
  CheckoutAnnulleretRoute: CheckoutAnnulleretRoute,
  CheckoutSuccesRoute: CheckoutSuccesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
